[tool.poetry]
name = "tiny-paper"
version = "0.1.0"
description = ""
authors = ["Fabian Damken"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
websockets = "^12.0"
tqdm = "^4.66.1"
markdownify = "^0.11.6"
pandas = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
